### ISSUE TITLE
empty message

### ISSUE THREAD

**Issue by LOORDyassin** [EL-Rayeb/ib3athli#2]

**Comment by LOORDyassin** [comment]
When I press the send button and the message is empty, the message is sen.
![image](https://github.com/EL-Rayeb/ib3athli/assets/151580584/7637eae4-e983-418a-95f6-a7ce0c1c6106)

**Comment by Ali-Cheikh** [comment]
> When I press the send button and the message is empty, the message is sent. ![image](https://private-user-images.githubusercontent.com/151580584/317504437-7637eae4-e983-418a-95f6-a7ce0c1c6106.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NzEyNzIsIm5iZiI6MTcxMTU3MDk3MiwicGF0aCI6Ii8xNTE1ODA1ODQvMzE3NTA0NDM3LTc2MzdlYWU0LWU5ODMtNDE4YS05NWY2LWE3Y2UwYzFjNjEwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QyMDIyNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGUzMzAxNmVlZGI3ZGFlNDA2ZWNlODNmMmEzOGRhOWRiNGUzODY0M2IyNmZlNTJkN2JiZDg1MjIzYjFmOWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C9oZ_rs87RhJTNTmMTtbeIM4q_bcPmGZFPs6TNYuqE8)

# that issue was fixed 
## _the ability to send empty messege ben fixed_ 

**date problem solved** : 3/26/2024
